### ISSUE TITLE
Replies should say who they were to, not from.

### ISSUE THREAD

**Issue by ryantheleach** [Rosuav/LispWhispers#1]
![image](https://user-images.githubusercontent.com/141554/70397864-d1acc000-1a65-11ea-8044-89584d00d771.png)

Otherwise seeing my username listed multiple times isn't so useful.

**Comment by Rosuav** [comment]
Agreed. I already have some TODOs relating to the display of sent whispers. Will work on this at the same time (maybe tonight). Thanks for testing!

**Comment by Rosuav** [comment]
Sorted. Lemme know if that looks good for you!
